name: CI

on:
  push:
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract
        run: Expand-Archive ngrok.zip

      - name: Auth
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - name: Enable Remote Desktop
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set User Authentication
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Set Local User Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389

      - name: Start SSH Server
        run: |
          # Install the OpenSSH Server feature
          Install-WindowsFeature -Name OpenSSH-Server

          # Start the SSH Server service
          Start-Service sshd

          # Enable the SSH Server service to start automatically
          Set-Service -Name sshd -StartupType 'Automatic'

          # Configure SSH to use a specific username and password (replace USERNAME and PASSWORD with your desired values)
          Set-Content -Path "C:\ProgramData\ssh\sshd_config" -Value @"
          PermitRootLogin no
          PasswordAuthentication yes
          PermitEmptyPasswords no
          Match User USERNAME
          PasswordAuthentication yes
          ForceCommand chpasswd
          "@

          # Restart the SSH Server for changes to take effect
          Restart-Service sshd
